#!/usr/bin/env python3
import sys
#Questão 6

a = sys.argv[1]

favthings = {'Book' : 'Senhor dos Anéis', 'Song' : 'Angra - Late Redemption', 'Tree' : 'Syrup Tree', 'Organismo' : 'Fungo'}

if a in favthings:
	print(favthings[a])
else:
	print('{} não é uma key do dicionário, confira e tente novamente.'.format(a))
	print('As keys presentes no dicionário são:')
	for key in favthings:
		print(key)
